"""make required fields non-nullable

Revision ID: 86f7462fec5b
Revises: e847f88a6f31
Create Date: 2026-08-19 19:58:32.416409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f7462fec5b'
down_revision: Union[str, Sequence[str], None] = 'e847f88a6f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 's3_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 's3_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
